hostname: ATLR1
site: ATL
ci_name: router-atl-01
expected_assignment_group: Network Operations

incoming_event:
  event_id: "EVT10011"
  incident_id: "INC20011"
  severity: "major"
  timestamp: "2026-04-16T15:00:00Z"

loopback_ip: 10.0.0.1/32

interfaces:
  - name: GigabitEthernet0/0
    description: WAN uplink
    ip: 192.168.10.1/24
  - name: GigabitEthernet0/1
    description: LAN segment
    ip: 10.10.10.1/24
    
ospf_networks:
   - 10.0.0.1 0.0.0.0 area 0
   - 192.168.10.0 0.0.0255 area 0
