hostname: CLTR2
loopback_ip: 10.0.0.2/32

interfaces:
  - name: GigabitEthernet0/0
    description: WAN uplink
    ip: 192.168.10.2/24
  - name: GigabitEthernet0/1
    description: Branch LAN
    ip: 10.20.20.1/24

ospf_process: 1
ospf_networks:
   - 10.0.0.2 0.0.0.0 area 0
   - 192.168.10.0 0.0.0255 area 0
