hostname: CLTR2
site: CLT
ci_name: router-clt-02
expected_assignment_group: Network Operations

incoming_event:
  event_id: "EVT10021"
  incident_id: "INC20021"
  severity: "major"
  timestamp: "2026-04-16T15:00:00Z"

loopback_ip: 10.0.0.2/32

interfaces:
  - name: GigabitEthernet0/0
    description: WAN uplink
    ip: 192.168.10.2/24
  - name: GigabitEthernet0/1
    description: Branch LAN
    ip: 10.20.20.1/24

ospf_networks:
   - 10.0.0.2 0.0.0.0 area 0
   - 192.168.10.0 0.0.0255 area 0
