hostname CLTR2

banner motd ^
There's nothing like me except me.
If you are not me, LEAVE.
Configuration managed through automation.

^

interface Loopback0
 ip address 10.0.0.2/32
 
interface GigabitEthernet0/0
 description WAN uplink
 ip address 192.168.10.2/24
 no shutdown
 
interface GigabitEthernet0/1
 description Branch LAN
 ip address 10.20.20.1/24
 no shutdown
 
 
router ospf 1
 network 10.0.0.2 0.0.0.0 area 0
 network 192.168.10.0 0.0.0255 area 0
